/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AbuttonComponents: typeof import('./src/components/abuttonComponents.vue')['default']
    AddModal: typeof import('./src/components/AddModal.vue')['default']
    ButtonComponents: typeof import('./src/components/buttonComponents.vue')['default']
    Cap: typeof import('./src/components/user/Cap.vue')['default']
    EditDialog: typeof import('./src/components/admin/EditDialog.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    Framework: typeof import('./src/components/file/Framework.vue')['default']
    HomeComponents: typeof import('./src/components/HomeComponents.vue')['default']
    Icon: typeof import('./src/components/file/icon.vue')['default']
    Lebar: typeof import('./src/components/lebar.vue')['default']
    Login: typeof import('./src/components/user/Login.vue')['default']
    Mkdir: typeof import('./src/components/fileop/mkdir.vue')['default']
    Navbar: typeof import('./src/components/navbar.vue')['default']
    PageContainer: typeof import('./src/components/admin/PageContainer.vue')['default']
    Register: typeof import('./src/components/user/register.vue')['default']
    Rename: typeof import('./src/components/fileop/rename.vue')['default']
    Reset: typeof import('./src/components/user/reset.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectDepartment: typeof import('./src/components/admin/SelectDepartment.vue')['default']
    Share: typeof import('./src/components/fileop/share.vue')['default']
    Upload: typeof import('./src/components/fileop/upload.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
